import re

with open('src/components/StudioHomePage.tsx', 'r') as f:
    code = f.read()

# Update the main heading and paragraph
heading_search = r"<h1 className=\"text-3xl sm:text-5xl lg:text-6xl font-black tracking-tight text-white font-\['Cinzel',serif\] leading-tight\">\s*Create Full Anime Series & Kinetic Shorts\s*</h1>\s*<p className=\"text-base sm:text-lg text-slate-300 max-w-2xl mx-auto font-sans leading-relaxed\">\s*Enterprise zero-to-episode animation studio\. Turn a single prompt into screenplay breakdowns, persistent 4K character Soul ID vaults, and fully compiled master videos with multi-track lip sync and sequel continuity\.\s*</p>"
heading_replace = """<h1 className="text-3xl sm:text-5xl lg:text-6xl font-black tracking-tight text-white font-['Cinzel',serif] leading-tight">
            Create Complete Manga Series with Flawless Continuity
          </h1>
          <p className="text-base sm:text-lg text-slate-300 max-w-2xl mx-auto font-sans leading-relaxed">
            Enterprise zero-to-chapter AI manga platform. Turn a single prompt into rich screenplay breakdowns, persistent character turnarounds, and beautifully structured manga pages with continuous visual storytelling.
          </p>"""
code = re.sub(heading_search, heading_replace, code)

# Update the architecture cards
cards_search = r"\{\/\* Neon PostgreSQL Architecture \*\/\}.*?\{\/\* Modest Prepaid Wallet Guard \*\/\}"
cards_replace = """{/* Community Manga Gallery */}
        <div 
          onClick={() => alert("Community Manga Gallery is launching soon! You will be able to inspect full chapters and short stories generated by our users.")}
          className="bg-slate-900/60 border border-slate-800 hover:border-sky-500/40 rounded-2xl p-6 cursor-pointer transition-all hover:bg-slate-900 group space-y-3"
        >
          <div className="flex items-center justify-between">
            <div className="h-10 w-10 rounded-xl bg-sky-500/10 border border-sky-500/30 flex items-center justify-center text-sky-400 group-hover:scale-110 transition-transform">
              <BookOpen className="h-5 w-5" />
            </div>
            <span className="text-[10px] font-mono text-sky-400 bg-sky-500/10 px-2 py-0.5 rounded">
              Coming Soon
            </span>
          </div>
          <div>
            <h4 className="font-bold text-sm text-slate-100 font-['Cinzel',serif]">Community Manga Gallery</h4>
            <p className="text-xs text-slate-400 mt-1">
              Inspect examples of full manga chapters, short stories, and single pages created using our platform.
            </p>
          </div>
        </div>

        {/* AI Layout Engine */}
        <div 
          className="bg-slate-900/60 border border-slate-800 hover:border-emerald-500/40 rounded-2xl p-6 transition-all hover:bg-slate-900 group space-y-3"
        >
          <div className="flex items-center justify-between">
            <div className="h-10 w-10 rounded-xl bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center text-emerald-400 group-hover:scale-110 transition-transform">
              <Wand2 className="h-5 w-5" />
            </div>
            <span className="text-[10px] font-mono text-emerald-400 bg-emerald-500/10 px-2 py-0.5 rounded">
              DeepSeek + Qwen
            </span>
          </div>
          <div>
            <h4 className="font-bold text-sm text-slate-100 font-['Cinzel',serif]">Precision Layout Engines</h4>
            <p className="text-xs text-slate-400 mt-1">
              Harness the power of our structured LLMs to map narrative beats directly onto stunning Manga spreads.
            </p>
          </div>
        </div>

        {/* Modest Prepaid Wallet Guard */}"""
code = re.sub(cards_search, cards_replace, code, flags=re.DOTALL)

with open('src/components/StudioHomePage.tsx', 'w') as f:
    f.write(code)

