import re

with open('src/components/MangaStudioHomePage.tsx', 'r') as f:
    code = f.read()

# Update paragraph
para_search = r"<p className=\"text-base sm:text-lg text-slate-300 max-w-2xl mx-auto font-sans leading-relaxed\">\s*Zero frame-render GPU bills\. Leverage immutable turnaround sheets to ink consistent, high-fidelity Gekiga manga panels\. Lay vector speech containers locally using Pillow directly on your VPS\.\s*</p>"
para_replace = """<p className="text-base sm:text-lg text-slate-300 max-w-2xl mx-auto font-sans leading-relaxed">
            Effortlessly craft world-class, story-driven manga from a single prompt. Leverage our powerful AI layout engines and strictly enforced character identity vaults to generate beautiful, continuous chapters—complete with expressive panels and dialogue—instantly.
          </p>"""
code = re.sub(para_search, para_replace, code)

# Update python inspect button
btn_search = r"<button\s*onClick=\{onOpenPythonModal\}\s*className=\"w-full sm:w-auto flex items-center justify-center gap-2 px-6 py-3\.5 rounded-xl bg-slate-950 hover:bg-slate-900 border border-slate-800 text-slate-300 text-xs font-bold transition-all cursor-pointer\"\s*>\s*<FileCode className=\"h-4 w-4 text-amber-400\" />\s*<span>Inspect manga_tasks\.py</span>\s*</button>"
btn_replace = """<button
              onClick={() => alert("Community Manga Gallery is launching soon! You will be able to inspect full chapters and short stories generated by our users.")}
              className="w-full sm:w-auto flex items-center justify-center gap-2 px-6 py-3.5 rounded-xl bg-slate-950 hover:bg-slate-900 border border-slate-800 text-slate-300 text-xs font-bold transition-all cursor-pointer"
            >
              <BookOpen className="h-4 w-4 text-amber-400" />
              <span>View Community Manga Gallery (Coming Soon)</span>
            </button>"""
code = re.sub(btn_search, btn_replace, code)

with open('src/components/MangaStudioHomePage.tsx', 'w') as f:
    f.write(code)

